// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import HelloController from "./hello_controller"
import PrivacyVaultController from "./privacy_vault_controller"
import RelationshipTemplateFieldsController from "./relationship_template_fields_controller"
import TimezoneController from "./timezone_controller"

application.register("hello", HelloController)
application.register("privacy-vault", PrivacyVaultController)
application.register("relationship-template-fields", RelationshipTemplateFieldsController)
application.register("timezone", TimezoneController)
